[workspace]
resolver = "3"
members = ["crates/freekerf-library", "crates/freekerf-library-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/freekerf/library"
rust-version = "1.85"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
