//! JSON Schema generation (from the Rust model) and validation.
//!
//! The committed files in `schema/v1/` are generated by [`SchemaKind::render`];
//! `freekerf-library schema --check` (and a test) keep them in sync.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::model::{HazardList, Machine, Material};
use crate::package::Index;

/// Base URL where the published schemas live.
pub const SCHEMA_BASE_URL: &str = "https://raw.githubusercontent.com/freekerf/library/main/schema/v1";

/// Document kinds that have a schema.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SchemaKind {
    /// `material.schema.json`.
    Material,
    /// `machine.schema.json`.
    Machine,
    /// `hazards.schema.json`.
    Hazards,
    /// `index.schema.json` (release package index).
    Index,
}

impl SchemaKind {
    /// Every kind.
    pub const ALL: [SchemaKind; 4] = [
        SchemaKind::Material,
        SchemaKind::Machine,
        SchemaKind::Hazards,
        SchemaKind::Index,
    ];

    /// File name inside `schema/v1`.
    pub fn file_name(self) -> &'static str {
        match self {
            SchemaKind::Material => "material.schema.json",
            SchemaKind::Machine => "machine.schema.json",
            SchemaKind::Hazards => "hazards.schema.json",
            SchemaKind::Index => "index.schema.json",
        }
    }

    /// JSON Schema generated from the model.
    pub fn schema(self) -> Value {
        let schema = match self {
            SchemaKind::Material => schemars::schema_for!(Material),
            SchemaKind::Machine => schemars::schema_for!(Machine),
            SchemaKind::Hazards => schemars::schema_for!(HazardList),
            SchemaKind::Index => schemars::schema_for!(Index),
        };
        let mut value = schema.to_value();
        if let Value::Object(map) = &mut value {
            map.insert(
                "$id".into(),
                Value::String(format!("{SCHEMA_BASE_URL}/{}", self.file_name())),
            );
        }
        value
    }

    /// Pretty-printed schema file content (with trailing newline).
    pub fn render(self) -> String {
        let mut text = serde_json::to_string_pretty(&self.schema()).expect("schema serializes");
        text.push('\n');
        text
    }
}

/// Writes every schema into `dir`.
pub fn write_all(dir: &Path) -> io::Result<Vec<PathBuf>> {
    fs::create_dir_all(dir)?;
    SchemaKind::ALL
        .iter()
        .map(|kind| {
            let path = dir.join(kind.file_name());
            fs::write(&path, kind.render())?;
            Ok(path)
        })
        .collect()
}

/// Returns the schema files in `dir` that are missing or differ from the generated ones.
pub fn stale(dir: &Path) -> Vec<PathBuf> {
    SchemaKind::ALL
        .iter()
        .map(|kind| dir.join(kind.file_name()))
        .zip(SchemaKind::ALL)
        .filter(|(path, kind)| fs::read_to_string(path).ok().as_deref() != Some(kind.render().as_str()))
        .map(|(path, _)| path)
        .collect()
}

/// Compiled validators for every schema kind.
pub struct SchemaSet {
    material: jsonschema::Validator,
    machine: jsonschema::Validator,
    hazards: jsonschema::Validator,
    index: jsonschema::Validator,
}

impl SchemaSet {
    /// Compiles the generated schemas.
    pub fn compile() -> Self {
        let build =
            |kind: SchemaKind| jsonschema::validator_for(&kind.schema()).expect("generated schema is valid");
        Self {
            material: build(SchemaKind::Material),
            machine: build(SchemaKind::Machine),
            hazards: build(SchemaKind::Hazards),
            index: build(SchemaKind::Index),
        }
    }

    /// Validates `instance`, returning one message per violation (`<json pointer>: <message>`).
    pub fn validate(&self, kind: SchemaKind, instance: &Value) -> Vec<String> {
        let validator = match kind {
            SchemaKind::Material => &self.material,
            SchemaKind::Machine => &self.machine,
            SchemaKind::Hazards => &self.hazards,
            SchemaKind::Index => &self.index,
        };
        validator
            .iter_errors(instance)
            .map(|e| {
                let path = e.instance_path().to_string();
                let path = if path.is_empty() { "/".to_string() } else { path };
                format!("{path}: {e}")
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn schemas_have_id_and_units() {
        let material = SchemaKind::Material.schema();
        assert_eq!(
            material["$id"],
            json!(format!("{SCHEMA_BASE_URL}/material.schema.json"))
        );
        let text = SchemaKind::Material.render();
        assert!(text.ends_with('\n'));
        assert!(text.contains("\"x-unit\": \"mm/min\""));
        for kind in SchemaKind::ALL {
            assert!(kind.file_name().ends_with(".schema.json"));
        }
    }

    #[test]
    fn validates_instances() {
        let set = SchemaSet::compile();
        let errors = set.validate(SchemaKind::Hazards, &json!({"hazards": []}));
        assert_eq!(errors.len(), 1, "{errors:?}");
        assert!(errors[0].starts_with("/hazards"));
        let errors = set.validate(SchemaKind::Machine, &json!({}));
        assert!(!errors.is_empty());
        assert!(errors[0].starts_with("/:"));
        let errors = set.validate(SchemaKind::Material, &json!({"id": "Bad Id"}));
        assert!(errors.iter().any(|e| e.starts_with("/id")));
    }

    #[test]
    fn write_and_detect_stale() {
        let dir = tempfile::tempdir().unwrap();
        assert_eq!(stale(dir.path()).len(), 4);
        let written = write_all(dir.path()).unwrap();
        assert_eq!(written.len(), 4);
        assert!(stale(dir.path()).is_empty());
        fs::write(dir.path().join("machine.schema.json"), "{}").unwrap();
        assert_eq!(stale(dir.path()), vec![dir.path().join("machine.schema.json")]);
    }
}
